// <auto-generated />
using System;
using COMP586.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace COMP586.Migrations
{
    [DbContext(typeof(COMP586VehiclesDBContext))]
    partial class COMP586VehiclesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("COMP586.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("ownerID");

                    b.Property<int>("Dob")
                        .HasColumnType("int")
                        .HasColumnName("DOB");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("lastName");

                    b.Property<string>("LicenseNum")
                        .IsRequired()
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("varchar(17)");

                    b.Property<int>("LicenseStatus")
                        .HasColumnType("int");

                    b.Property<string>("StateResidence")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("stateResidence")
                        .IsFixedLength(true);

                    b.HasKey("OwnerId");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("COMP586.Models.VehicleInfo", b =>
                {
                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicleID");

                    b.Property<string>("Color")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("color");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("make");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int")
                        .HasColumnName("mileage");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("model");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int")
                        .HasColumnName("modelYear");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("ownerID");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("VIN");

                    b.HasKey("VehicleId");

                    b.HasIndex("OwnerId");

                    b.ToTable("VehicleInfo");
                });

            modelBuilder.Entity("COMP586.Models.VehicleInfo", b =>
                {
                    b.HasOne("COMP586.Models.Owner", "Owner")
                        .WithMany("VehicleInfos")
                        .HasForeignKey("OwnerId")
                        .HasConstraintName("FK_VehicleInfo_Owner");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("COMP586.Models.Owner", b =>
                {
                    b.Navigation("VehicleInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
